CREATE TABLE reports (
	id SERIAL PRIMARY KEY,

	parsed_on TIMESTAMPTZ NOT NULL,
	parse_success BOOLEAN NOT NULL DEFAULT FALSE,

	university UNIVERSITY_T NOT NULL,
	covers_range TSTZRANGE NOT NULL,
	pages INTEGER NOT NULL,
	crimes_count INTEGER NOT NULL
)
